spring.application.name: demo

# Set log level for org.springframework.web
logging.level.org.springframework.web: DEBUG

# Enable color in console if supported
spring.output.ansi.enabled: always

# Data Source
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://192.168.1.123:3306/nation
    driver-class-name: org.mariadb.jdbc.Driver
    username: you forgot username
    password: you forgot password
    hikari:
      idle-timeout: 10000